
spring:
  output:
    ansi:
      enabled: "ALWAYS"
  application:
    name: "department-service"
  datasource:
    url: "jdbc:h2:mem:department-db;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    open-in-view: 'false'
    show-sql: 'false'
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  config:
    import: "optional:configserver:http://localhost:8088"
management:
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    org.hibernate.SQL: "DEBUG"

