server:
  port: 8082
  servlet:
    context-path: "/office"
spring:
  application:
    name: "employee-service"
  output:
    ansi:
      enabled: "ALWAYS"
  datasource:
    url: "jdbc:h2:mem:employee-db"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
  jpa:
    hibernate:
      auto-ddl: "create"
    open-in-view: false
    show-sql: false
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
management:
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    org.hibernate.SQL: "DEBUG"

data:
  path: "ms-office-employee/src/main/resources/data/"